### ISSUE TITLE
exiting with book while in street causes a lot of bugs

### ISSUE THREAD

**Issue by seapunkshark** [robertfwallis/toontownsfunnyfarm-issue-tracker#15]
if you enter rickety road, exit to the main menu using your book, go back (to any toon) you will spawn in a bugged playground and rickety road hybrid, even if you try another toon.
cannot attack cogs while in the hybrid
![image](https://user-images.githubusercontent.com/59255257/72733937-538a2000-3bb2-11ea-9013-157766657f7a.png)
if you manage to enter rickety road then the cogs and the npcs are bugged
![image](https://user-images.githubusercontent.com/59255257/72734468-2be78780-3bb3-11ea-922d-c342cd6f2ace.png)
if you enter a building in rickety road then exit it will spawn outside, on the road. if you enter it, you can talk to the npc but you can only exit through the door. exiting through the door crashes the game. same thing happens in playground
![image](https://user-images.githubusercontent.com/59255257/72734637-8e408800-3bb3-11ea-8849-fa109ec9e395.png)
can only be solved by relogging

**Comment by NathanX-S** [comment]
Fixed for v1.4.3, thanks for the report! 👍
